--TRUNCATE TABLE ORDERS
--TRUNCATE TABLE ORDERDETAILS
--TRUNCATE TABLE INVOICES
--TRUNCATE TABLE INVOICEDETAILS
--TRUNCATE TABLE PAYMENTS
 

DECLARE @I AS INT=0
DECLARE @ITEMCOUNT AS INT
DECLARE @ADDRESSID AS INT 
DECLARE @ORDERID AS INT
DECLARE @ITEMID AS INT
DECLARE @USERID AS INT
DECLARE @DATE AS DATETIME
DECLARE @TOTALPRICE AS FLOAT
DECLARE @PRICE AS FLOAT
DECLARE @AMOUNT AS INT
DECLARE @INVOICEID AS INT

WHILE @I<10000
BEGIN
SELECT TOP 1  @USERID=ID FROM ETRADE4.DBO.USERS ORDER BY NEWID()
SELECT TOP 1 @ADDRESSID=ID FROM ADDRESS WHERE USERID=@USERID  ORDER BY NEWID()
WHILE @ADDRESSID IS NULL
BEGIN
	SELECT TOP 1  @USERID=ID FROM ETRADE4.DBO.USERS ORDER BY NEWID()
	SELECT TOP 1 @ADDRESSID=ID FROM ADDRESS WHERE USERID=@USERID  ORDER BY NEWID()
END

SET @DATE=DATEADD(DAY,RAND()*450,'20190101')
SET @DATE=DATEADD(HOUR,RAND()*24,@DATE) 
SET @DATE=DATEADD(MINUTE,RAND()*60,@DATE) 
SET @DATE=DATEADD(SECOND,RAND()*60,@DATE) 
SET @ITEMCOUNT=1+(RAND()*10)
DECLARE @K AS INT=0
INSERT INTO ORDERS(USERID,DATE_,TOTALPRICE,STATUS_,ADDRESSID)
	VALUES (@USERID,@DATE,0,0,@ADDRESSID)
SET @ORDERID=@@IDENTITY

WHILE @K<@ITEMCOUNT
BEGIN
	SELECT TOP 1  @ITEMID=ID,@PRICE=UNITPRICE*(1+(RAND()*0.2)),@AMOUNT=1+(RAND()*10) FROM ITEMS WHERE UNITPRICE>0 ORDER BY NEWID()
	INSERT INTO ORDERDETAILS (ORDERID,ITEMID,AMOUNT,UNITPRICE,LINETOTAL)
	VALUES(@ORDERID,@ITEMID,@AMOUNT,@PRICE,@PRICE*@AMOUNT)
	


SET @K=@K+1
END --@K
--UPDATE ORDERS SET TOTALPRICE=ROUND((SELECT SUM(LINETOTAL) FROM ORDERDETAILS WHERE ORDERID=@ORDERID),2)
--WHERE ID=@ORDERID

INSERT INTO PAYMENTS
(ORDERID,PAYMENTTYPE,DATE_,ISOK,APPROVECODE,PAYMENTTOTAL)

SELECT ID,1+(RAND()*2),DATEADD(SECOND,2,@DATE),1,'APPRV'+REPLICATE('0',10-LEN(@ORDERID))+CONVERT(VARCHAR,@ORDERID),TOTALPRICE
FROM ORDERS WHERE ID=@ORDERID

--UPDATE ORDERS SET STATUS_=1 WHERE ID=@ORDERID

	INSERT INTO INVOICES(ORDERID,DATE_,ADDRESSID,CARGOFICHENO,TOTALPRICE)
	SELECT   ID,DATEADD(MINUTE,RAND()*60,DATEADD(HOUR,10+(RAND()*24),@DATE)) AS DATE_,
	ADDRESSID,'CRGF'+REPLICATE('0',10-LEN(@ORDERID))+CONVERT(VARCHAR,@ORDERID) AS CARGOFICHENO,TOTALPRICE
	 FROM ORDERS WHERE ID=@ORDERID
 SET @INVOICEID=@@IDENTITY
	 INSERT INTO INVOICEDETAILS
	 (INVOICEID,ORDERDETAILID,ITEMID,AMOUNT,UNITPRICE,LINETOTAL)
	 SELECT @INVOICEID,ID,ITEMID,AMOUNT,UNITPRICE,LINETOTAL
	 FROM ORDERDETAILS WHERE ORDERID=@ORDERID

--UPDATE ORDERS SET STATUS_=2 WHERE ID=@ORDERID
SET @I=@I+1
END-- @I
SELECT * FROM ORDERS
SELECT * FROM ORDERDETAILS
SELECT * FROM PAYMENTS
SELECT * FROM INVOICES
SELECT * FROM INVOICEDETAILS




 
 